version: '3.3'

services:
  localstack:
    image: "localstack/localstack:3.3"
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    environment:
      - SERVICES=s3
  init:
    build: .
    environment:
    - AWS_DEFAULT_REGION=us-east-1
    - AWS_ACCESS_KEY_ID=foobar
    - AWS_SECRET_ACCESS_KEY=foobar
    depends_on:
      - localstack
    restart: "no"
    entrypoint: ["python3", "init.py"]
  # main:
  #   build: .
  #   environment:
  #   - AWS_DEFAULT_REGION=us-east-1
  #   - AWS_ACCESS_KEY_ID=foobar
  #   - AWS_SECRET_ACCESS_KEY=foobar
  #   - DOCKER_COMPOSE="1"
  #   - ENDPOINT_URL="http://localstack:4566"
  #   depends_on:
  #     - localstack
  #     - init