version: '3.3'

services:
  localstack:
    image: "localstack/localstack:3.3"
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    environment:
      - SERVICES=s3
  app:
    build: .
    environment:
    - AWS_DEFAULT_REGION=us-east-1
    - AWS_ACCESS_KEY_ID=foobar
    - AWS_SECRET_ACCESS_KEY=foobar
    depends_on:
      - localstack